# JDK paths configuration
# Format: <jdk_version> <java_home_path>
8   /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home
11  /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home
17  /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
